"""
FolderChef — Recipe Data Models
=================================

This module defines the data models for AI-generated recipes.

WHAT IS A RECIPE?
    A recipe is a structured set of instructions for cooking a meal.
    In FolderChef, recipes are special because they are generated by AI
    using ingredients that are currently ON SALE at Dutch supermarkets.

THE RECIPE FLOW:
    1. User sees weekly discounts
    2. User clicks "Generate Recipes" (or it happens automatically)
    3. Backend sends discounted items to the AI service
    4. AI generates Recipe objects with ingredients, steps, and cost estimates
    5. Frontend displays the recipes to the user

EXAMPLE RECIPE JSON:
    {
        "title": "Romige Kaas-Broccoli Soep",
        "description": "A creamy cheese and broccoli soup...",
        "servings": 4,
        "prep_time_minutes": 10,
        "cook_time_minutes": 25,
        "estimated_cost": 6.50,
        "ingredients": [...],
        "instructions": [...],
        "tags": ["vegetarian", "budget", "dutch"]
    }
"""

from typing import Optional

from pydantic import BaseModel, Field, field_validator

from app.models.discount import VALID_LABELS


class RecipeIngredient(BaseModel):
    """
    A single ingredient needed for a recipe.

    This links a recipe ingredient back to a potential discount item,
    so the frontend can show which ingredients are currently on sale.

    Attributes:
        name (str):
            The ingredient name.
            Example: "Goudse kaas jong belegen"

        quantity (str):
            How much of this ingredient is needed.
            Example: "200g", "2 stuks", "1 blik"

        is_discounted (bool):
            Whether this ingredient is currently on sale.
            True = it's in this week's supermarket deals.

        estimated_price (float | None):
            Estimated cost for the needed quantity (in EUR).

        original_price (float | None):
            Regular price per unit in EUR if on sale. Used to show savings.

        discount_price (float | None):
            Sale price per unit in EUR if on sale.

        discount_item_id (str | None):
            ID of the matching DiscountItem, if this ingredient is on sale.
            This lets the frontend link directly to the deal.
    """

    name: str = Field(
        ...,
        description="Ingredient name",
        examples=["Goudse kaas jong belegen", "broccoli"],
    )
    quantity: str = Field(
        ...,
        description="Amount needed",
        examples=["200g", "2 stuks", "1 blik", "500ml"],
    )
    is_discounted: bool = Field(
        default=False,
        description="Whether this ingredient is currently on sale",
    )
    estimated_price: Optional[float] = Field(
        default=None,
        description="Estimated cost in EUR for this quantity",
        ge=0,
    )
    original_price: Optional[float] = Field(
        default=None,
        description="Regular price per unit in EUR (if on sale)",
        ge=0,
    )
    discount_price: Optional[float] = Field(
        default=None,
        description="Sale price per unit in EUR (if on sale)",
        ge=0,
    )
    discount_item_id: Optional[str] = Field(
        default=None,
        description="ID of matching discount item (if on sale)",
    )


class Recipe(BaseModel):
    """
    A complete recipe generated by AI using discounted ingredients.

    This is the core data model of FolderChef — a budget-friendly recipe
    built around ingredients that are currently on sale.

    Attributes:
        id (str | None):
            Unique identifier (assigned by database).

        title (str):
            Recipe title.
            Example: "Romige Kaas-Broccoli Soep"

        description (str):
            Short description of the recipe (1-2 sentences).

        servings (int):
            Number of people this recipe serves.

        prep_time_minutes (int):
            Preparation time in minutes.

        cook_time_minutes (int):
            Cooking time in minutes.

        estimated_cost (float):
            Total estimated cost in EUR for all ingredients.

        savings_percentage (float | None):
            How much cheaper this meal is compared to non-sale prices.

        ingredients (list[RecipeIngredient]):
            List of ingredients with quantities.

        instructions (list[str]):
            Step-by-step cooking instructions.

        tags (list[str]):
            Tags for filtering (e.g., "vegetarian", "quick", "dutch").

        image_url (str | None):
            URL to a generated or placeholder recipe image.

        supermarkets (list[str]):
            Which supermarkets have the deals used in this recipe.
    """

    id: Optional[str] = Field(
        default=None,
        description="Unique identifier (assigned by database)",
    )
    title: str = Field(
        ...,
        description="Recipe title",
        examples=["Romige Kaas-Broccoli Soep"],
    )
    description: str = Field(
        ...,
        description="Short recipe description",
    )
    servings: int = Field(
        default=4,
        description="Number of servings",
        ge=1,
    )
    prep_time_minutes: int = Field(
        default=15,
        description="Preparation time in minutes",
        ge=0,
    )
    cook_time_minutes: int = Field(
        default=30,
        description="Cooking time in minutes",
        ge=0,
    )
    estimated_cost: float = Field(
        ...,
        description="Total estimated cost in EUR",
        ge=0,
    )
    savings_percentage: Optional[float] = Field(
        default=None,
        description="Percentage saved compared to full-price shopping",
    )
    ingredients: list[RecipeIngredient] = Field(
        default_factory=list,
        description="List of ingredients with quantities",
    )
    instructions: list[str] = Field(
        default_factory=list,
        description="Step-by-step cooking instructions",
    )
    tags: list[str] = Field(
        default_factory=list,
        description="Tags for filtering",
        examples=[["vegetarian", "budget", "quick", "dutch"]],
    )
    image_url: Optional[str] = Field(
        default=None,
        description="Recipe image URL",
    )
    supermarkets: list[str] = Field(
        default_factory=list,
        description="Supermarkets with deals used in this recipe",
    )


class RecipeGenerateRequest(BaseModel):
    """
    Request model for generating recipes from discounts.

    The frontend sends this when the user wants new recipe suggestions.

    Attributes:
        supermarkets (list[str]):
            Which supermarkets to use discounts from.
            Default: both Albert Heijn and Jumbo.

        num_recipes (int):
            How many recipes to generate.
            Default: 5

        dietary_preferences (list[str]):
            User's dietary preferences for filtering.
            Examples: ["vegetarian", "gluten-free", "halal"]

        max_budget_per_meal (float | None):
            Maximum budget per meal in EUR.
            None = no budget limit.

        user_prompt (str | None):
            Optional user message to guide recipe generation (e.g. "quick dinner", "no oven").

        label_filter (list[str] | None):
            Optional list of labels (max 5). Only discount items with at least one
            of these labels are sent to the AI. Labels must be from VALID_LABELS.
    """

    supermarkets: list[str] = Field(
        default=["albert_heijn", "jumbo"],
        description="Supermarkets to use discounts from",
    )
    num_recipes: int = Field(
        default=5,
        description="Number of recipes to generate",
        ge=1,
        le=20,
    )
    dietary_preferences: list[str] = Field(
        default_factory=list,
        description="Dietary preferences",
        examples=[["vegetarian", "gluten-free"]],
    )
    max_budget_per_meal: Optional[float] = Field(
        default=None,
        description="Max budget per meal in EUR",
        ge=0,
    )
    user_prompt: Optional[str] = Field(
        default=None,
        description="User message to guide recipe generation",
        max_length=2000,
    )
    label_filter: Optional[list[str]] = Field(
        default=None,
        description="Filter discount items by these labels (max 5); only these are sent to AI",
        max_length=5,
    )

    @field_validator("label_filter")
    @classmethod
    def validate_label_filter(cls, v: Optional[list[str]]) -> Optional[list[str]]:
        if v is None or len(v) == 0:
            return v
        if len(v) > 5:
            raise ValueError("At most 5 labels allowed")
        invalid = [lbl for lbl in v if lbl not in VALID_LABELS]
        if invalid:
            raise ValueError(f"Invalid labels (must be from fixed set): {invalid}")
        return v


class RecipeGenerateResponse(BaseModel):
    """
    Response model after generating recipes.

    Attributes:
        recipes (list[Recipe]):
            The list of AI-generated recipes.

        total_recipes (int):
            How many recipes were generated.

        discounts_used (int):
            How many discount items were used across all recipes.
    """

    recipes: list[Recipe] = Field(
        default_factory=list,
        description="Generated recipes",
    )
    total_recipes: int = Field(
        default=0,
        description="Number of recipes generated",
    )
    discounts_used: int = Field(
        default=0,
        description="Number of discount items used",
    )
