/**
 * FolderChef — Recipe TypeScript Types
 * =======================================
 *
 * These types mirror the Pydantic models on the backend.
 * They define the shape of recipe data in the frontend.
 *
 * KEEP IN SYNC with: backend/app/models/recipe.py
 */

/**
 * Fixed set of food labels from the database (cleaned_products.labels).
 * User can select up to 5 to filter which discounted items are sent to the AI.
 */
export const VALID_LABELS: readonly string[] = [
  "bio",
  "fresh",
  "meat",
  "fish",
  "vegetable",
  "fruit",
  "dairy",
  "eggs",
  "cheese",
  "ready-to-eat",
  "bakery",
  "pantry",
  "cooking aids",
  "frozen",
  "snack",
  "candy",
  "beverage",
  "salad",
  "asia",
  "non-food",
] as const;

/**
 * A single ingredient in a recipe.
 *
 * Links to a potential discount item so the UI can highlight
 * which ingredients are currently on sale.
 *
 * @property name - Ingredient name (e.g., "Goudse kaas").
 * @property quantity - Amount needed (e.g., "200g", "2 stuks").
 * @property is_discounted - Whether this ingredient is currently on sale.
 * @property estimated_price - Estimated cost in EUR for this quantity.
 * @property original_price - Regular price per unit in EUR (if on sale).
 * @property discount_price - Sale price per unit in EUR (if on sale).
 * @property discount_item_id - ID of matching discount item (if on sale).
 */
export interface RecipeIngredient {
  name: string;
  quantity: string;
  is_discounted: boolean;
  estimated_price: number | null;
  original_price?: number | null;
  discount_price?: number | null;
  discount_item_id: string | null;
}

/**
 * A complete AI-generated recipe.
 *
 * This is the core data model displayed in the frontend.
 * Recipes are generated by AI using discounted ingredients.
 *
 * @property id - Unique identifier (null if not saved).
 * @property title - Recipe title (e.g., "Romige Kaas-Broccoli Soep").
 * @property description - Short description (1-2 sentences).
 * @property servings - Number of people this serves.
 * @property prep_time_minutes - Preparation time in minutes.
 * @property cook_time_minutes - Cooking time in minutes.
 * @property estimated_cost - Total cost in EUR.
 * @property savings_percentage - How much cheaper vs full-price shopping.
 * @property ingredients - List of ingredients with quantities.
 * @property instructions - Step-by-step cooking instructions.
 * @property tags - Filtering tags (e.g., "vegetarian", "quick").
 * @property image_url - Recipe image URL.
 * @property supermarkets - Which supermarkets have deals used.
 */
export interface Recipe {
  id: string | null;
  title: string;
  description: string;
  servings: number;
  prep_time_minutes: number;
  cook_time_minutes: number;
  estimated_cost: number;
  savings_percentage: number | null;
  ingredients: RecipeIngredient[];
  instructions: string[];
  tags: string[];
  image_url: string | null;
  supermarkets: string[];
}

/**
 * Request body for generating recipes.
 *
 * Sent to POST /api/recipes/generate.
 *
 * @property supermarkets - Which supermarkets to use deals from.
 * @property num_recipes - How many recipes to generate.
 * @property dietary_preferences - User's dietary restrictions.
 * @property max_budget_per_meal - Optional max budget per meal in EUR.
 * @property user_prompt - Optional user message to guide recipe generation.
 * @property label_filter - Optional list of labels (max 5); only items with these labels are sent to AI.
 */
export interface RecipeGenerateRequest {
  supermarkets: string[];
  num_recipes: number;
  dietary_preferences: string[];
  max_budget_per_meal?: number;
  user_prompt?: string;
  label_filter?: string[];
}

/**
 * Response from recipe generation.
 *
 * Returned by POST /api/recipes/generate.
 *
 * @property recipes - The generated recipes.
 * @property total_recipes - Number of recipes generated.
 * @property discounts_used - Number of discount items used across recipes.
 */
export interface RecipeGenerateResponse {
  recipes: Recipe[];
  total_recipes: number;
  discounts_used: number;
}
